# Generated by Django 4.0.5 on 2022-06-16 13:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Payer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('second_name', models.CharField(max_length=100)),
                ('shares', models.IntegerField()),
                ('phone_number', models.CharField(max_length=11)),
                ('added_time', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='PayRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('paid_shares', models.IntegerField(default=1)),
                ('pay_date', models.DateTimeField()),
                ('payer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kooperatif_api.payer')),
            ],
        ),
    ]
